# A-Maze-ing

## Create a $h \times w$ cell

In [11]:
from numpy import zeros, mean, array


size = (6, 8)
maze = []
for i in range(size[0]):
    row = ""
    for j in range(size[1]):
        row += 'f'
    maze.append(row)
for i in maze:
    print(i)
visited = zeros(size)
if visited.shape[0] < 7 and visited.shape[1] < 9:
    print("The '42' cannot be printed in a maze this size.")
else:
    hs, ws = visited.shape[0] // 2 - 2, visited.shape[1] // 2 - 3
    pos_42 = (
        (hs, ws), (hs + 1, ws), (hs + 2, ws), (hs + 2, ws + 1),
        (hs + 2, ws + 2), (hs + 3, ws + 2), (hs + 4, ws + 2),
        (hs, ws + 4), (hs, ws + 5), (hs, ws + 6), (hs + 1, ws + 6),
        (hs + 2, ws + 6), (hs + 2, ws + 5), (hs + 2, ws + 4),
        (hs + 3, ws + 4), (hs + 4, ws + 4), (hs + 4, ws + 5),
        (hs + 4, ws + 6)
    )
    for i in pos_42:
        visited[i[0]][i[1]] = -1
    lab_42 = [
        (hs + 1, ws + 3),
        (hs + 1, ws + 4),
        (hs + 1, ws + 5),
        (hs + 3, ws + 5),
        (hs + 3, ws + 6),
        (hs + 3, ws + 7),
    ]
    perfect = False
    if perfect is False:
        lab_42.extend(
            [
                (hs + 2, ws + 3),
                (hs + 3, ws + 3),
                (hs + 4, ws + 3),
                (hs + 5, ws + 3)
            ]
        )
    for i in lab_42:
        visited[i[0], i[1]] = 1
print(visited)

ffffffff
ffffffff
ffffffff
ffffffff
ffffffff
ffffffff
The '42' cannot be printed in a maze this size.
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


## Manage errors

In [ ]:
class MazeError(Exception):
    def __init__(self, msg: str):
        self.msg = msg

in_bounds = [
    start[0] < 0,
    start[1] < 0,
    start[0] > size[0],
    start[1] > size[1],
    end[0] < 0,
    end[1] < 0,
    end[0] > size[0],
    end[1] > size[1]
]
if False in in_bounds:
    raise MazeError("Start or end of the maze are out of bounds")

if visited.shape[0] > 6 and visited.shape[1] > 8:
    in_42 = []
    in_42.extend([True for i in pos_42 if i[0] == start[0] and i[1] == start[1]])
    in_42.extend([True for i in pos_42 if i[0] == end[0] and i[1] == end[1]])
    if True in in_42:
        raise MazeError("Start or end of the maze are inside the 42")